name: bpulsa
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  validate: ^1.6.0
  http: any
  progress_hud: "^0.2.2"
  sqflite: "^0.11.0"
  path_provider: ^0.3.1
  firebase_admob: ^0.5.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/loginImage.png
    - assets/logo.png
    - assets/bg.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf

flutter_icons:
  image_path: "assets/logo.png" 
  android: true
  ios: true